chore(pipeline): fixed directory path

diff --git a/.github/workflows/deployment.yaml b/.github/workflows/deployment.yaml
--- a/.github/workflows/deployment.yaml
+++ b/.github/workflows/deployment.yaml
@@ -17,21 +17,22 @@ jobs:
           echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./key.pem
           chmod 600 ./key.pem
           mkdir -p ~/.ssh
-          ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts
+          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
 
           ssh -i ./key.pem ${{ secrets.SSH_USERNAME }}@${{ secrets.HOST }} -T <<EOF
-          if [ -d "~/ONDC-automation-framework/automation-mock-service" ]; then
-            echo "Repository already exists, cleaning up"
-            cd ~/ONDC-automation-framework/automation-mock-service && git pull origin main
+          REPO_DIR=~/ONDC-automation-framework/automation-mock-service
+          if [ -d "\$REPO_DIR" ]; then
+            echo "Repository already exists, pulling latest changes"
+            cd \$REPO_DIR && git pull origin main
           else
             echo "Cloning repository"
-            git clone https://github.com/ONDC-Official/automation-mock-service.git ~/ONDC-automation-framework/automation-mock-service
+            git clone https://github.com/ONDC-Official/automation-mock-service.git \$REPO_DIR
           fi
           EOF
 
-      - name: Write secrets to .env
+      - name: Write secrets to .env on EC2
         run: |
-          echo "Writing secrets to .env file in the correct directory"
+          echo "Writing secrets to .env file"
           ssh -i ./key.pem ${{ secrets.SSH_USERNAME }}@${{ secrets.HOST }} <<EOF
           echo "REDIS_USERNAME=${{ secrets.REDIS_USERNAME }}" >> ~/ONDC-automation-framework/automation-mock-service/.env
           echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> ~/ONDC-automation-framework/automation-mock-service/.env
@@ -43,9 +44,14 @@ jobs:
 
       - name: Automation Mock Server Deployment
         run: |
-          ssh -o ServerAliveInterval=30 -o TCPKeepAlive=yes -T -i ./key.pem ${{ secrets.SSH_USERNAME }}@${{ secrets.HOST }} <<EOF
-          ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts
+          echo "Deploying with Docker Compose"
+          ssh -T -i ./key.pem ${{ secrets.SSH_USERNAME }}@${{ secrets.HOST }} <<EOF
           cd ~/ONDC-automation-framework/automation-mock-service
-          cp ~/.env ~/ONDC-automation-framework/automation-mock-service/
+
+          if [ ! -f .env ]; then
+            echo ".env file not found!"
+            exit 1
+          fi
+
           sudo docker-compose up -d --build
           EOF
